# Generated by Django 5.2.13 on 2026-05-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_employeeidnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='employee',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='employee',
            name='house',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='House No, House name, Road name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Pin code'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='employee_profiles/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='employee',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Village, Post Office, City'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('SYSADMIN', 'Sys-Admin'), ('SALESMAN', 'Salesman'), ('ACCOUNTANT', 'Accountant'), ('DRIVER', 'Driver'), ('WATCHMAN', 'Watchman'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20, verbose_name='Role'),
        ),
    ]
