# Generated by Django on 2026-07-31

from django.db import migrations, models
import django.db.models.deletion


def migrate_employee_roles(apps, schema_editor):
    EmployeeRole = apps.get_model('users', 'EmployeeRole')
    Employee = apps.get_model('users', 'Employee')

    # Ensure OWNER role exists in EmployeeRole table
    owner_role, _ = EmployeeRole.objects.get_or_create(
        name='OWNER',
        defaults=dict(
            display_name='Owner',
            is_builtin=True,
            employee_manage=True,
            dealers_manage=True,
            products_manage=True,
            collection_manage=True,
            orders_manage=True,
            attendance_manage=True,
            visit_manage=True,
            leads_manage=True,
            milage_manage=True,
        )
    )

    # Cache roles by uppercase name
    role_map = {r.name.upper(): r for r in EmployeeRole.objects.all()}

    # Copy matching EmployeeRole reference from old string 'role' to new 'role_fk' ForeignKey
    for emp in Employee.objects.all():
        role_str = str(emp.role).upper() if emp.role else 'EMPLOYEE'
        if role_str in role_map:
            emp.role_fk = role_map[role_str]
        else:
            emp.role_fk = role_map.get('EMPLOYEE')
        if emp.role_fk:
            emp.save(update_fields=['role_fk'])


def reverse_migrate_employee_roles(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_employeerole_milage_manage'),
    ]

    operations = [
        # 1. Add temporary ForeignKey field `role_fk`
        migrations.AddField(
            model_name='employee',
            name='role_fk',
            field=models.ForeignKey(
                blank=True,
                help_text='Foreign key referencing EmployeeRole.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='employees',
                to='users.employeerole',
                verbose_name='Role',
            ),
        ),
        # 2. Data migration: convert existing string role names to `role_fk` references
        migrations.RunPython(migrate_employee_roles, reverse_code=reverse_migrate_employee_roles),
        # 3. Remove old string `role` field
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        # 4. Rename `role_fk` to `role`
        migrations.RenameField(
            model_name='employee',
            old_name='role_fk',
            new_name='role',
        ),
    ]
