# Generated by Django on 2026-07-31

from django.db import migrations


def remove_owner_role_from_db(apps, schema_editor):
    EmployeeRole = apps.get_model('users', 'EmployeeRole')
    Employee = apps.get_model('users', 'Employee')

    # Find OWNER role if it exists
    owner_roles = EmployeeRole.objects.filter(name='OWNER')
    if owner_roles.exists():
        for owner_role in owner_roles:
            # Set role = None for any employee pointing to OWNER role
            Employee.objects.filter(role=owner_role).update(role=None)
        owner_roles.delete()


def reverse_remove_owner_role(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_employee_role'),
    ]

    operations = [
        migrations.RunPython(remove_owner_role_from_db, reverse_code=reverse_remove_owner_role),
    ]
