# Generated by Django 5.2.13 on 2026-08-20 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_role_hierarchy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeerole',
            options={'ordering': ['hierarchy_level', 'name'], 'verbose_name': 'Employee Role', 'verbose_name_plural': 'Employee Roles'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Foreign key referencing EmployeeRole (null for OWNER).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.employeerole', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='display_name',
            field=models.CharField(help_text="Human-readable label, e.g. 'Senior Manager'", max_length=100),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='hierarchy_level',
            field=models.PositiveSmallIntegerField(default=99, help_text='Hierarchy rank. 1 = Owner (highest authority). Higher number = lower authority. A role can only manage roles whose level is strictly greater.'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='is_builtin',
            field=models.BooleanField(default=False, help_text='Built-in roles cannot be deleted.'),
        ),
    ]
