# Generated by Django 5.2.13 on 2026-05-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdealer',
            name='address',
        ),
        migrations.AddField(
            model_name='subdealer',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='subdealer',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='subdealer',
            name='shop_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='House No, House name, Road name'),
        ),
        migrations.AddField(
            model_name='subdealer',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='subdealer',
            name='store_picture',
            field=models.ImageField(blank=True, null=True, upload_to='dealer_store_pictures/'),
        ),
        migrations.AddField(
            model_name='subdealer',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Village, Post Office, City'),
        ),
        migrations.AlterField(
            model_name='subdealer',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Pin code'),
        ),
    ]
