# Generated by Django 5.2.13 on 2026-06-05 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_remove_subdealer_address_subdealer_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subdealer',
            name='temp_handeler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_handler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subdealer',
            name='temp_handeler_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subdealer',
            name='country',
            field=models.CharField(default='India', max_length=255, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subdealer',
            name='district',
            field=models.CharField(default=1, max_length=255, verbose_name='District'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subdealer',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subdealer',
            name='gst_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subdealer',
            name='pincode',
            field=models.CharField(default=1, max_length=6, verbose_name='Pin code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subdealer',
            name='shop_number',
            field=models.CharField(default=1, max_length=255, verbose_name='House No, House name, Road name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subdealer',
            name='state',
            field=models.CharField(default=1, max_length=255, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subdealer',
            name='street',
            field=models.CharField(default=1, max_length=255, verbose_name='Village, Post Office, City'),
            preserve_default=False,
        ),
    ]
