# Generated by Django 5.2.13 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
