# Generated by Django 5.2.13 on 2026-05-26 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_km', models.FloatField()),
                ('start_image', models.ImageField(upload_to='attendance/start/')),
                ('start_location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_latitude', models.FloatField(blank=True, null=True)),
                ('start_longitude', models.FloatField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('work_now', models.BooleanField(default=True)),
                ('end_km', models.FloatField(blank=True, null=True)),
                ('end_image', models.ImageField(blank=True, null=True, upload_to='attendance/end/')),
                ('end_location', models.CharField(blank=True, max_length=255, null=True)),
                ('end_latitude', models.FloatField(blank=True, null=True)),
                ('end_longitude', models.FloatField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('total_km', models.FloatField(blank=True, null=True)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'created_at'], name='tracking_at_employe_739f80_idx')],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Dealer', 'Dealer'), ('Client', 'Client')], default='Dealer', max_length=20)),
                ('gps_image', models.ImageField(upload_to='visits/images/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_visits', to='dealers.subdealer')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_collection', to='sales.collection')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_visits', to='dealers.subdealer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_order', to='sales.order')),
            ],
            options={
                'indexes': [models.Index(fields=['dealer', 'employee', 'created_at'], name='tracking_vi_dealer__26b52e_idx')],
            },
        ),
    ]
