# Generated by Django 5.2.13 on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='auto_checkout',
            field=models.BooleanField(default=False),
        ),
    ]
