# Generated by Django 5.2.13 on 2026-08-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_visit_mileage_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='milage',
            new_name='tracking_mi_employe_fa7435_idx',
            old_name='tracking_milage_emp_date_idx',
        ),
        migrations.AlterField(
            model_name='milage',
            name='return_to_home',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='milage',
            name='total_distance_travelled',
            field=models.FloatField(default=0.0),
        ),
    ]
