# Generated by Django 5.2.13 on 2026-08-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_rename_tracking_milage_emp_date_idx_tracking_mi_employe_fa7435_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='eod_tomorrow_plan',
            field=models.TextField(blank=True, default='', help_text='Tomorrow visit plan area submitted in EOD report', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='eod_visited_areas',
            field=models.TextField(blank=True, default='', help_text="Today's visited areas submitted in EOD report", null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sod_collection_target',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text="Today's collection target submitted in SOD", max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sod_market_plan',
            field=models.TextField(blank=True, default='', help_text="Today's market visit plan area/meeting submitted in SOD", null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sod_sales_target',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text="Today's sales target submitted in SOD", max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sod_visits_target',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="Today's counter visit target count submitted in SOD", null=True),
        ),
    ]
