# Generated by Django 5.2.13 on 2026-07-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='device',
            new_name='notificatio_user_id_155101_idx',
            old_name='notifications_user_id_4523bb_idx',
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='notificatio_push_to_2a81a5_idx',
            old_name='notifications_push_token_index',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_4e3567_idx',
            old_name='notificatio_recipie_ec1e55_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_f39341_idx',
            old_name='notificatio_recipie_60100f_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_status_d92267_idx',
            old_name='notificatio_status_56ef5e_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_priorit_bf8ea0_idx',
            old_name='notificatio_priorit_10a12e_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_notific_f2898f_idx',
            old_name='notificatio_notific_9d09f7_idx',
        ),
    ]
