# Generated by Django 5.2.13 on 2026-06-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional',
        ),
    ]
