# Generated by Django 5.2.13 on 2026-08-20 13:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_order_additional_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('in_transit', 'In-transit'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(help_text='Target year (e.g. 2026)', validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.PositiveSmallIntegerField(help_text='Target month (1 to 12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('sales_target', models.DecimalField(decimal_places=2, default=0.0, help_text='Target sales amount in currency', max_digits=14)),
                ('collection_target', models.DecimalField(decimal_places=2, default=0.0, help_text='Target collection amount in currency', max_digits=14)),
                ('visits_target', models.PositiveIntegerField(default=0, help_text='Target dealer/subdealer visits count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='The sales employee this target is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_targets', to=settings.AUTH_USER_MODEL)),
                ('target_setby', models.ForeignKey(blank=True, help_text='Admin who set or last updated this target', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_monthly_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['employee', 'year', 'month'], name='sales_month_employe_f33645_idx'), models.Index(fields=['year', 'month'], name='sales_month_year_941fe3_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'year', 'month'), name='unique_employee_monthly_target')],
            },
        ),
        migrations.CreateModel(
            name='SpecialTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', help_text="Campaign name e.g., 'Diwali Sprint 2026'", max_length=255)),
                ('from_date', models.DateField(help_text='Target duration start date')),
                ('to_date', models.DateField(help_text='Target duration end date')),
                ('sales_target', models.DecimalField(decimal_places=2, default=0.0, help_text='Target sales amount in currency', max_digits=14)),
                ('collection_target', models.DecimalField(decimal_places=2, default=0.0, help_text='Target collection amount in currency', max_digits=14)),
                ('visits_target', models.PositiveIntegerField(default=0, help_text='Target dealer/subdealer visits count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='The sales employee this target is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='special_targets', to=settings.AUTH_USER_MODEL)),
                ('target_setby', models.ForeignKey(blank=True, help_text='Admin who set or last updated this target', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_special_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-from_date'],
                'indexes': [models.Index(fields=['employee', 'from_date', 'to_date'], name='sales_speci_employe_c09f81_idx'), models.Index(fields=['from_date', 'to_date'], name='sales_speci_from_da_a3220c_idx')],
            },
        ),
    ]
