# Generated by Django 5.2.13 on 2026-08-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_order_status_monthlytarget_specialtarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlytarget',
            name='id',
            field=models.CharField(editable=False, help_text="Target ID in 'YYYY-MM' format (e.g. '2026-08')", max_length=7, primary_key=True, serialize=False),
        ),
    ]
